included:
    - Sources
disabled_rules:
    - force_cast
    - force_try
    - cyclomatic_complexity
    - function_body_length
    - large_tuple
identifier_name:
    min_length: 2
    allowed_symbols: ["_"]
    validates_start_with_lowercase: false
switch_case_alignment:
    indented_cases: true
